spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    change-log: classpath:liquibase-changelog.xml
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 3600000
server:
  port: 8090

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    change-log: classpath:liquibase-changelog.xml
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 3600000
server:
  port: 8090
